filters:
  min_roe:
  max_de:
  min_fcf:
  min_revenue_cagr_5yr:
  min_pat_cagr_5yr:
  min_opm:
  max_pe:
  max_pb:
  min_dividend_yield:
  min_icr:
  min_market_cap:
  min_net_profit:
  min_eps_cagr:
  min_asset_turnover:
  min_sales: